# Generated by Django 5.1.5 on 2025-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Place',
        ),
        migrations.AddField(
            model_name='registerdb',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
