# Generated by Django 5.1.5 on 2025-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_registerdb_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
