# Generated by Django 5.1.5 on 2025-01-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_registerdb_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='location',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='username',
        ),
        migrations.AddField(
            model_name='registerdb',
            name='ConfirmPassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
