# Generated by Django 5.1.5 on 2025-01-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_rental_images_rental_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='image',
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rentals/')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.rental')),
            ],
        ),
    ]
