# Generated by Django 5.1.5 on 2025-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_rental_email_remove_rental_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
